server:
    port: 8080

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
spring:
  application:
      name: gateway

  cloud:
      gateway:
          routes:
              # MICROSERVICIO companies
             -  id: companies
                uri: lb://companies
                predicates:
                - Path=/companies/**

              # MICROSERVICIO inovices
             - id: companies
               uri: lb://invoices
               predicates:
                  - Path=/invoices/**
logging:
    level:
        org.springframework.cloud.gateway: debug